services:
  core_gw:
    build:
      context: gw-build
      args:
        IGNITION_VERSION: 8.1.48
    hostname: core_gw
    ports:
      - 9091:8088
    volumes:
      - core_gw-data:/usr/local/bin/ignition/data
     # - ./gw-init/gateway.gwbk:/restore.gwbk
     # - ./gw-init/gateway-uuid.txt:/usr/local/bin/ignition/data/.uuid
     # - ./gw-init/gateway-metro-keystore:/usr/local/bin/ignition/data/local/metro-keystore
    networks:
      - core-network
    environment:
      - IGNITION_EDITION=standard
      - GATEWAY_ADMIN_PASSWORD=katlego
      - ACCEPT_IGNITION_EULA=Y
    command: >
      -n core_gw
      -m 2048
     # -r /restore.gwbk
  core_sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
      - MSSQL_PID=Developer
    ports:
      - 1434:1433
    volumes:
      - core_sql-data:/var/opt/mssql
    restart: always
    networks:
      core-network:
        aliases:
          - main-db
  core_smtp:
    image: dockage/mailcatcher:0.8.2
    ports:
      - 1081:1080
      - 1026:1025
    networks:
      core-network:
        aliases:
          - mail-srvr  
networks:
  core-network:
volumes:
  core_gw-data:
  core_sql-data:
