services:
  core-gw:
    image: inductiveautomation/ignition:8.1.48 
    hostname: core-gw
    container_name: core-gw
    ports:
      - 9098:8088
    volumes:
      - gw-data:/usr/local/bin/ignition/data
   #   - ./gw-init/edge.gwbk:/restore.gwbk
     # - ./gw-init/edge-uuid.txt:/usr/local/bin/ignition/data/.uuid
    #  - ./gw-init/edge-metro-keystore:/usr/local/bin/ignition/data/local/metro-keystore
#      - ./pylib/speciallibrary.py:/usr/local/bin/ignition/user-lib/pylib/speciallibrary.py
    networks:
      - core-network
   # labels:
   #   tsdproxy.enable: true
   #   tsdproxy.ephemeral: false
    environment:
      - IGNITION_EDITION=standard
      - GATEWAY_ADMIN_PASSWORD=katlego
      - ACCEPT_IGNITION_EULA=Y
    command: >
      -n core-gateway
      -m 2048
    #  -r /restore.gwbk
  smtp:
    image: dockage/mailcatcher:0.8.2
    container_name: smtp
    ports:
      - 1081:1080
      - 1026:1025
   # labels:
   #   tsdproxy.enable: true
   #   tsdprody.ephemeral: false
    networks:
      core-network:
        aliases:
          - smtp

volumes:
  gw-data:

networks:
  core-network:
